game.name = Phantom Hunt
game.command = java -jar phantom-hunt.jar client localhost:2222
game.description.file = index.html
game.screenshot.file = screenshot.png
game.server.command = java -jar phantom-hunt.jar server 2222
game.use = true
game.year = 2026
game.developers = Vera Bitterlin, Ismail Dzemaili, Jan Valentin Haag, Silas Weber, Hermes Reisner