image: eclipse-temurin:25-jdk

stages:
  - build

build:
  stage: build
  before_script:
    - chmod +x gradlew
  script:
    - ./gradlew build-cs108
  artifacts:
    paths:
      - build/libs/phantom-hunt.jar
    expire_in: 2 weeks
