plugins {
    id 'application'
    id 'java'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'ch.unibas.dmi.dbis'
version = '0.0.1-ALPHA'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

ext { // von application zu ext geändert
    clientMainClass = 'ch.unibas.dmi.dbis.cs108.example.gui.javafx.ClientGuiMain'
    serverMainClass = 'ch.unibas.dmi.dbis.cs108.example.server.ServerApp'

}

repositories {
    mavenCentral()
}

javafx {
    version = "25.0.2"
    modules = ['javafx.controls', 'javafx.fxml', 'javafx.base']
}

dependencies {
    implementation 'org.apache.logging.log4j:log4j-api:2.25.3'
    implementation 'org.apache.logging.log4j:log4j-core:2.25.3'

    testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher:1.10.0")
}

test {
    useJUnitPlatform()
}

tasks.register('clientFatJar', Jar) {
    group = 'build'
    description = 'Assembles a runnable fat JAR for the client application.'

    archiveClassifier = 'client'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    manifest {
        attributes('Main-Class': clientMainClass)
    }

    // include your compiled classes/resources
    from(sourceSets.main.output)

    // make sure runtimeClasspath is resolved before we try to zipTree it
    dependsOn(configurations.runtimeClasspath)

    // unpack runtime deps into the jar
    from({
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    })
}

tasks.register('serverFatJar', Jar) {
    group = 'build'
    description = 'Assembles a runnable fat JAR for the server application.'

    archiveClassifier = 'server'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    manifest {
        attributes('Main-Class': serverMainClass)
    }

    // include your compiled classes/resources
    from(sourceSets.main.output)

    // make sure runtimeClasspath is resolved before we try to zipTree it
    dependsOn(configurations.runtimeClasspath)

    // unpack runtime deps into the jar
    from({
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    })
}
